name: cpu-macos-build-and-test

on:
  push:
    paths-ignore:
      - '**.md'
      - 'images/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'images/**'

jobs:
  build:
    name: Build and test

    strategy:
      matrix:
        config: [ '' ] # , '-DPBRT_WITH_RGB=False' ] , '-DPBRT_DBG_LOGGING=True', '-DPBRT_FLOAT_AS_DOUBLE=True' ]
      fail-fast: false

    runs-on: macos-latest

    steps:
    - name: Checkout pbrt
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Checkout rgb2spectrum tables
      uses: actions/checkout@v4
      with:
        repository: mmp/rgb2spectrum
        path: build
      
    - name: Get cmake
      uses: lukka/get-cmake@latest

    - name: Configure
      run: |
        cd build
        cmake .. -DPBRT_USE_PREGENERATED_RGB_TO_SPECTRUM_TABLES=True -DCMAKE_INSTALL_PREFIX=./deploy -DPBRT_WITH_OIDN=True ${{ matrix.config }}
      
    - name: Build
      run: cmake --build build --config Release --target install
      
    - name: Test
      if: ${{ matrix.config == '-DPBRT_WITH_RGB=False' }}
      run: ./pbrt_test
      working-directory: build

    - name: Save MacOS executable
      if: ${{ matrix.config == '' }}
      uses: actions/upload-artifact@v4
      with:
        name: pbrt-v4_${{ matrix.os }}
        path: "${{ github.workspace }}/build/deploy/bin/"
        retention-days: 1
